#!/bin/bash

# inspect AWS account

lr=$(perl -e 'print "-" x 50')
regions=(
	#$(aws ec2 describe-regions --query 'Regions[].RegionName' --output text)
	# "eu-north-1"
    # "ap-south-1"
    # "eu-west-3"
    # "eu-west-2"
    # "eu-west-1"
    # "ap-northeast-2"
    # "ap-northeast-1"
    # "sa-east-1"
    # "ca-central-1"
    # "ap-southeast-1"
    # "ap-southeast-2"
    # "eu-central-1"
    "us-east-1"
    "us-east-2"
    # "us-west-1"
    # "us-west-2"
)
for region in "${regions[@]}"
do
echo
echo "$lr"
echo "Region: $region"
echo "$lr"
echo "EC2 Instances"
aws ec2 describe-instances --query 'Reservations[].Instances[].{State:State.Name,Id:InstanceId}' --region "$region"
done

