#!/bin/bash
yum update -y
yum install -y --setopt=protected_multilib=false glibc.i686 libstdc++.i686
useradd rust
mkdir /home/rust/steamcmd; cd /home/rust/steamcmd
wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
tar zxf steamcmd_linux.tar.gz
chown -R rust:rust /home/rust/steamcmd
mkdir -p /home/rust/rustserver/server/server1/cfg
echo ownerid 76561198002558771 >> /home/rust/rustserver/server/server1/cfg/users.cfg
chown -R rust:rust /home/rust/rustserver

su rust -c "./steamcmd.sh +login anonymous +force_install_dir /home/rust/rustserver +app_update 258550 +quit"
cd /home/rust/rustserver

rcon_pw=$(aws secretsmanager \
get-secret-value \
--secret-id rcon_pw \
--query "SecretString" \
--output text \
--region us-east-1)

cat > /home/rust/start_server <<EOF
cd /home/rust/rustserver
nohup \
 ./RustDedicated \
 -batchmode \
 +rcon.password "$rcon_pw" \
 +rcon.port 28016 \
 +server.port 28015 \
 +server.level "Procedural Map" \
 +server.seed 1234 \
 +server.worldsize 4000 \
 +server.maxplayers 10  \
 +server.hostname "ABC123 TEST SERVER" \
 +server.description "my rust server" \
 +server.url "http://yourwebsite.com" \
 +server.headerimage "http://yourwebsite.com/serverimage.jpg" \
 +server.identity "server1" \
 > nohup.out 2>&1
EOF

chmod +x /home/rust/start_server
chown rust:rust /home/rust/start_server
su - rust -c /home/rust/start_server &
